const TEMPLATE_ID = TEMPLATE_SESSION_ID;
function relativeTime(value) { if (!value) return 'No edits yet'; const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return 'Edited just now'; if (seconds < 3600) return `Edited ${Math.floor(seconds / 60)}m ago`; if (seconds < 86400) return `Edited ${Math.floor(seconds / 3600)}h ago`; return `Edited ${Math.floor(seconds / 86400)}d ago`; }
function drawPreview(svg, items) {
  const NS = 'http://www.w3.org/2000/svg'; const W = 320; const H = 150; const pad = { l: 24, r: 14, t: 14, b: 20 }; const x0 = pad.l; const y0 = pad.t; const x1 = W - pad.r; const y1 = H - pad.b;
  svg.setAttribute('viewBox', `0 0 ${W} ${H}`); svg.innerHTML = `<rect x="${x0}" y="${y0}" width="${x1-x0}" height="${y1-y0}" fill="#F4F1E8" stroke="#DCD2BE"/><line x1="${(x0+x1)/2}" y1="${y0}" x2="${(x0+x1)/2}" y2="${y1}" stroke="#DCD2BE"/><line x1="${x0}" y1="${(y0+y1)/2}" x2="${x1}" y2="${(y0+y1)/2}" stroke="#DCD2BE"/>`;
  for (const item of items.filter(item => typeof item.x === 'number' && typeof item.y === 'number')) { const circle = document.createElementNS(NS, 'circle'); circle.setAttribute('cx', x0 + (item.x - 110) / 850 * (x1 - x0)); circle.setAttribute('cy', y0 + (item.y - 40) / 650 * (y1 - y0)); circle.setAttribute('r', '3.5'); circle.setAttribute('fill', CATS[item.category]?.[1] || '#24413A'); svg.appendChild(circle); }
}
async function loadDashboard() {
  const grid = document.getElementById('sessionGrid'); const errorBox = document.getElementById('dashboardError'); grid.innerHTML = '<p class="hint">Loading sessions...</p>'; errorBox.textContent = '';
  const { data: sessions, error } = await supabaseClient.from('sessions').select('id,name,created_at,updated_at,join_code').neq('id', TEMPLATE_ID).eq('is_ephemeral', false).order('updated_at', { ascending: false });
  if (error) { errorBox.textContent = 'Could not load sessions.'; console.error(error); return; }
  const ids = (sessions || []).map(session => session.id); let stakeholders = [];
  if (ids.length) { const result = await supabaseClient.from('stakeholders').select('session_id,x,y,category').in('session_id', ids); if (result.error) console.error(result.error); else stakeholders = result.data || []; }
  const bySession = {}; stakeholders.forEach(item => (bySession[item.session_id] ||= []).push(item)); grid.innerHTML = '';
  if (!sessions?.length) { grid.innerHTML = '<p class="hint">No sessions yet. Create one to get started.</p>'; return; }
  sessions.forEach(session => {
    const card = document.createElement('article'); card.className = 'session-card'; card.innerHTML = `<h2></h2><div class="session-meta"></div><svg class="preview" aria-label="Session preview"></svg><div class="card-actions"><button data-action="open">Open</button><button data-action="rename">Rename</button><button data-action="duplicate">Duplicate</button><button data-action="copy">Copy share link</button><button data-action="delete">Delete</button></div>`;
    card.querySelector('h2').textContent = session.name || 'Untitled session'; card.querySelector('.session-meta').textContent = `${relativeTime(session.updated_at)} · ${(bySession[session.id] || []).length} stakeholders · code ${session.join_code || '—'}`; drawPreview(card.querySelector('svg'), bySession[session.id] || []);
    card.querySelector('[data-action="open"]').onclick = () => { window.location.href = `mapping.html?session=${encodeURIComponent(session.id)}`; };
    card.querySelector('[data-action="copy"]').onclick = async () => { try { await navigator.clipboard.writeText(shareUrl(session.id)); notify('Session URL copied to clipboard.'); } catch (copyError) { notify('Unable to copy the session URL.'); console.error(copyError); } };
    card.querySelector('[data-action="rename"]').onclick = async () => { const name = prompt('Session name', session.name || ''); if (name === null || !name.trim()) return; const result = await supabaseClient.from('sessions').update({ name: name.trim(), updated_at: new Date().toISOString() }).eq('id', session.id); if (result.error) errorBox.textContent = 'Could not rename the session.'; else loadDashboard(); };
    card.querySelector('[data-action="duplicate"]').onclick = async () => { try { await cloneSession(session.id, `${session.name || 'Untitled session'} (copy)`); notify('Session duplicated.'); loadDashboard(); } catch (duplicateError) { errorBox.textContent = 'Could not duplicate the session.'; console.error(duplicateError); } };
    card.querySelector('[data-action="delete"]').onclick = async () => { if (!confirm(`Delete ${session.name || 'this session'}? This cannot be undone.`)) return; const links = await supabaseClient.from('influence_links').delete().eq('session_id', session.id); const items = await supabaseClient.from('stakeholders').delete().eq('session_id', session.id); const deleted = await supabaseClient.from('sessions').delete().eq('id', session.id); const failure = links.error || items.error || deleted.error; if (failure) { errorBox.textContent = 'Could not delete the session completely.'; console.error(failure); } else loadDashboard(); };
    grid.appendChild(card);
  });
}
async function createSession() { const name = prompt('Session name', 'Sibu Kamek Workshop'); if (name === null || !name.trim()) return; try { const session = await cloneSession(TEMPLATE_ID, name.trim()); window.location.href = `mapping.html?session=${encodeURIComponent(session.id)}`; } catch (error) { document.getElementById('dashboardError').textContent = 'Could not create the session.'; console.error(error); } }
document.getElementById('newSession').onclick = createSession;
document.getElementById('importSession').onclick = () => document.getElementById('importFile').click();
document.getElementById('importFile').onchange = async event => { const file = event.target.files[0]; event.target.value = ''; if (!file) return; try { const name = prompt('Name for imported session', file.name.replace(/\.json$/i, '') || 'Imported session'); if (name === null || !name.trim()) return; await importMapFile(file, name.trim()); notify('Session imported.'); loadDashboard(); } catch (error) { document.getElementById('dashboardError').textContent = error.message === 'Unexpected end of JSON input' ? 'The selected file is not valid JSON.' : error.message; console.error(error); } };
document.getElementById('dashboardSignOut').onclick = async () => { if (!confirm('Are you sure you want to sign out?')) return; clearDisplayName(); await supabaseClient.auth.signOut(); window.location.replace('index.html'); };
(async () => { const { data } = await supabaseClient.auth.getSession(); if (!data.session || !isAdminSession(data.session)) { window.location.replace('index.html'); return; } await loadDashboard(); supabaseClient.auth.onAuthStateChange((event, session) => { if (!session || !isAdminSession(session)) window.location.replace('index.html'); }); })();
